// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ServicingSystem.Entities;

[Table("JobPart")]
internal partial class JobPart
{
    [Key]
    [Column("JobPartID")]
    public int JobPartId { get; set; }

    [Column("JobID")]
    public int JobId { get; set; }

    [Column("PartID")]
    public int PartId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal SellingPrice { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("JobId")]
    [InverseProperty("JobParts")]
    public virtual Job Job { get; set; }

    [ForeignKey("PartId")]
    [InverseProperty("JobParts")]
    public virtual Part Part { get; set; }
}