// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesReturnSystem.Entities;

[Table("SaleRefund")]
internal partial class SaleRefund
{
    [Key]
    [Column("SaleRefundID")]
    public int SaleRefundId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SaleRefundDate { get; set; }

    [Column("SaleID")]
    public int SaleId { get; set; }

    [Required]
    [Column("EmployeeID")]
    [StringLength(450)]
    public string EmployeeId { get; set; }

    [Column(TypeName = "money")]
    public decimal TaxAmount { get; set; }

    [Column(TypeName = "money")]
    public decimal SubTotal { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("SaleId")]
    [InverseProperty("SaleRefunds")]
    public virtual Sale Sale { get; set; }

    [InverseProperty("SaleRefund")]
    public virtual ICollection<SaleRefundDetail> SaleRefundDetails { get; set; } = new List<SaleRefundDetail>();
}