// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReceivingSystem.Entities;

[Table("ReceiveOrderDetail")]
internal partial class ReceiveOrderDetail
{
	[Key]
	public int ReceiveOrderDetailId { get; set; }

	public int ReceiveOrderId { get; set; }

	public int PurchaseOrderDetailId { get; set; }

	public int QuantityReceived { get; set; }

	public bool RemoveFromViewFlag { get; set; }

	[ForeignKey("PurchaseOrderDetailId")]
	[InverseProperty("ReceiveOrderDetails")]
	public virtual PurchaseOrderDetail PurchaseOrderDetail { get; set; }

	[ForeignKey("ReceiveOrderId")]
	[InverseProperty("ReceiveOrderDetails")]
	public virtual ReceiveOrder ReceiveOrder { get; set; }
}
