// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReceivingSystem.Entities;

[Table("ReceiveOrder")]
internal partial class ReceiveOrder
{
	[Key]
	public int ReceiveOrderId { get; set; }

	public int PurchaseOrderId { get; set; }

	[Column(TypeName = "datetime")]
	public DateTime? ReceiveDate { get; set; }

	[StringLength(450)]
	public string EmployeeId { get; set; }

	public bool RemoveFromViewFlag { get; set; }

	[ForeignKey("PurchaseOrderId")]
	[InverseProperty("ReceiveOrders")]
	public virtual PurchaseOrder PurchaseOrder { get; set; }

	[InverseProperty("ReceiveOrder")]
	public virtual ICollection<ReceiveOrderDetail> ReceiveOrderDetails { get; set; } = new List<ReceiveOrderDetail>();

	[InverseProperty("ReceiveOrder")]
	public virtual ICollection<ReturnedOrderDetail> ReturnedOrderDetails { get; set; } = new List<ReturnedOrderDetail>();

	[InverseProperty("ReceiveOrder")]
	public virtual ICollection<UnorderedPurchaseItemCart> UnorderedPurchaseItemCarts { get; set; } = new List<UnorderedPurchaseItemCart>();
}
