// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReceivingSystem.Entities;

[Table("Vendor")]
internal partial class Vendor
{
	[Key]
	public int VendorId { get; set; }

	[Required]
	[StringLength(100)]
	public string VendorName { get; set; }

	[StringLength(20)]
	public string Phone { get; set; }

	[StringLength(200)]
	public string Address { get; set; }

	[StringLength(50)]
	public string City { get; set; }

	[StringLength(2)]
	public string ProvinceId { get; set; }

	[StringLength(6)]
	public string PostalCode { get; set; }

	public bool RemoveFromViewFlag { get; set; }

	[InverseProperty("Vendor")]
	public virtual ICollection<Part> Parts { get; set; } = new List<Part>();

	[InverseProperty("Vendor")]
	public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();
}
